---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dvwa-tls
  namespace: dvwa
spec:
  secretName: dvwa-tls
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - dvwa.amerintlxperts.com
    - app1.amerintlxperts.com
    - app2.amerintlxperts.com
    - app3.amerintlxperts.com
    - app4.amerintlxperts.com
    - app5.amerintlxperts.com
    - app6.amerintlxperts.com
    - app7.amerintlxperts.com
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
