---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dvwa-tls
  namespace: dvwa
spec:
  secretName: dvwa-tls
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - dvwa.40docs.com
    - app1.40docs.com
    - app2.40docs.com
    - app3.40docs.com
    - app4.40docs.com
    - app5.40docs.com
    - app6.40docs.com
    - app7.40docs.com
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
