---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dvwa
  name: secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dvwa
  name: read-secrets-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dvwa
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
