apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-init-script
  namespace: application
data:
  init-script.sh": |
    #!/bin/bash

    echo "Hi!"
    echo "My name is"
    echo "What?"
    echo "My name is"
    echo "Who?"
    echo "My name is"
    echo "Chika-chika"
    echo "Slim Shady"
