---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-svc
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ollama
roleRef:
  kind: ClusterRole
  name: svc-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ollama
  name: secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: ollama
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ollama
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
