apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-certificate
  namespace: docs
spec:
  template:
    spec:
      containers:
        - name: check-cert
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              while ! kubectl get secret docs-tls -n docs > /dev/null 2>&1; do
                echo "Waiting for certificate to be ready..."
                sleep 5
              done
              echo "Certificate is ready."
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
      restartPolicy: Never
  backoffLimit: 4

