---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: dvwa
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: dvwa-mariadb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa
  namespace: dvwa
  labels:
    app: dvwa
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: dvwa-mariadb
  type: NodePort
