---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pretix-tls
  namespace: pretix
spec:
  secretName: pretix-tls
  privateKey:
    rotationPolicy: Always
  commonName: 
  dnsNames:
    - 
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
