---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: read-svc
    namespace: video
subjects:
    - kind: ServiceAccount
      name: video
      apiGroup: ""
      namespace: video
roleRef:
    kind: ClusterRole
    name: svc-reader
    apiGroup: ""
