---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs-tls
  namespace: docs
spec:
  secretName: docs-tls
  privateKey:
    rotationPolicy: Always
  commonName: docs.amerintlxperts.com
  dnsNames:
    - docs.amerintlxperts.com
    - www.amerintlxperts.com
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
