---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs-tls
  namespace: docs
spec:
  secretName: docs-tls
  privateKey:
    rotationPolicy: Always
  commonName: docs.bankexample.com
  dnsNames:
    - docs.bankexample.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
