---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfigmap
  namespace: docs
data:
  default.conf: |
    server {
        listen       8080 default_server;
        server_name  _;
        port_in_redirect off;
        access_log /dev/stdout combined;
        error_log /dev/stderr warn;
        root /www/;
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
        add_header X-Content-Type-Options nosniff;

        # Allow unrestricted access to root and index.html
        location ~ ^/(|index.html)$ {
            try_files $uri $uri/ =404;
        }
        location ~* \.(css|js|ico|png)$ {
            try_files $uri =404;
        }
        location /search {
            try_files $uri $uri/ =404;
        }
        location /search/search_index.json {
            add_header Cache-Control "max-age=3600";
            add_header Surrogate-Control "max-age=3600";
        }
        location /assets {
            try_files $uri $uri/ =404;
        }
        location /theme {
            try_files $uri $uri/ =404;
        }
        location /agenda {
            try_files $uri $uri/ =404;
        }
        location ~ ^/(?!assets|search|theme|extra\.css|favicon\.ico|apple-touch-icon\.png|apple-touch-icon-precomposed\.png|agenda)(.*) {
            auth_basic "Restricted";
            auth_basic_user_file /etc/nginx/.htpasswd;
            try_files $uri $uri/ =404;
        }
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
