---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfigmap
  namespace: docs
data:
  default.conf: |
    server {
        listen       8080 default_server;
        server_name  _;
        port_in_redirect off;
        access_log /dev/stdout combined;
        error_log /dev/stderr warn;
        root /www/;
        
        # Error pages
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;

        # Security headers
        add_header X-Content-Type-Options nosniff;

        # Allow specific resources without restrictions
        location ~ ^/(assets|extra\.css|favicon\.ico|theme|hands-on-labs\.html|speakers\.html|references|(.css|.js|.ico|.png))$ {
            try_files $uri $uri/ =404;
        }

        # Serve root and index.html with restrictions
        location ~ ^/(|index.html)$ {
            auth_basic "Restricted";
            auth_basic_user_file /etc/nginx/.htpasswd;
            try_files $uri $uri/ =404;
        }

        # Search endpoint with caching
        location /search {
            try_files $uri $uri/ =404;
        }
        location /search/search_index.json {
            add_header Cache-Control "max-age=3600";
            add_header Surrogate-Control "max-age=3600";
        }

        # Allow unrestricted access to / (for HealthCheck)
        location = / {
            if ($request_method = HEAD) {
                return 200;
            }
            auth_basic "Restricted";
            auth_basic_user_file /etc/nginx/.htpasswd;
            try_files $uri $uri/ =404;
        }

        # Authentication for all other routes
        location ~ ^/(?!(assets|extra\.css|favicon\.ico|theme|hands-on-labs\.html|speakers\.html|references|search|(.css|.js|.ico|.png)))(.*) {
            auth_basic "Restricted";
            auth_basic_user_file /etc/nginx/.htpasswd;
            try_files $uri $uri/ =404;
        }

        # 50x error page
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }