apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfigmap
  namespace: hands-on-labs
data:
  default.conf: |
    server {
        listen       8080 default_server;
        server_name  _;
        port_in_redirect off;
        access_log /dev/stdout combined;
        error_log /dev/stderr warn;
        root /www/;
        
        # Error pages
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;

        # Security headers
        add_header X-Content-Type-Options nosniff;

        # Serve root and index.html without restrictions
        location ~ ^/(|index.html)$ {
            try_files $uri $uri/ =404;
        }

        # Serve specific file types
        location ~* \.(css|js|ico|png)$ {
            try_files $uri =404;
        }

        # Search endpoint with caching
        location /search {
            try_files $uri $uri/ =404;
        }
        location /search/search_index.json {
            add_header Cache-Control "max-age=3600";
            add_header Surrogate-Control "max-age=3600";
        }

        # Serve additional directories
        location /assets {
            try_files $uri $uri/ =404;
        }
        location /theme {
            try_files $uri $uri/ =404;
        }
        location /agenda {
            try_files $uri $uri/ =404;
        }

        # Allow specific unrestricted files
        location ~ ^/apple-touch-icon(-precomposed)?\.png$ {
            try_files $uri =404;
        }
        location = /Xperts1450x900.gif {
            try_files $uri =404;
        }
        location = /hands-on-labs.html {
            try_files $uri =404;
        }
        location /references {
            try_files $uri $uri/ =404;
        }

        # Allow unrestricted access to /speakers.html
        location = /speakers.html {
            try_files $uri =404;
        }

        # Allow unrestricted access to HealthCheck HEAD /
        location = / {
            if ($request_method = HEAD) {
                return 200;
            }
            try_files $uri $uri/ =404;
        }

        # Authentication for all other routes
        location ~ ^/(?!assets|search|theme|extra\.css|favicon\.ico|agenda|hands-on-labs\.html|speakers\.html|references)(.*) {
            auth_basic "Restricted";
            auth_basic_user_file /etc/nginx/.htpasswd;
            try_files $uri $uri/ =404;
        }

        # 50x error page
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
