---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfigmap
  namespace: docs
data:
  default.conf: |
    server {
      listen 8080 default_server;
      server_name _;
      port_in_redirect off;
      access_log /dev/stdout combined;
      error_log /dev/stdout info;
      root /www/;

      # Error pages
      error_page 404 /404.html;
      error_page 500 502 503 504 /50x.html;

      # Security headers
      add_header X-Content-Type-Options nosniff;

      # Allow unrestricted access to all paths except /ot, /cloud, /sase, /secops
      location / {
        # Security headers
        add_header X-Content-Type-Options nosniff;

        # Allow HEAD requests
        if ($request_method = HEAD) {
          return 200;
        }

        # Try serving requested resource or index
        try_files $uri $uri/ =404;
      }

      # Authentication for specific paths
      location ~ ^/(sase|ot|cloud|secops)(.*) {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;
        try_files $uri $uri/ =404;
      }

      # 50x error page
      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }
