---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
      volumes:
        - name: configmap-volume
          configMap:
            name: nginxconfigmap
