apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: docs
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: docs
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: docs
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: htpasswd-volume
              mountPath: /etc/nginx/.htpasswd
              subPath: htpasswd
            - name: configmap-volume
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: htpasswd-volume
          secret:
            secretName: htpasswd-secret
        - name: configmap-volume
          configMap:
            name: nginxconfigmap
