---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: docs
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
      annotations:
        configChecksum: "{{ checksum .ConfigMap }}"
    spec:
      containers:
        - name: docs
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: htpasswd-volume
              mountPath: /etc/nginx/.htpasswd
              subPath: htpasswd
            - name: configmap-volume
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: htpasswd-volume
          secret:
            secretName: htpasswd-secret
        - name: configmap-volume
          configMap:
            name: nginxconfigmap
