---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: docs-hpa
  namespace: docs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docs
  minReplicas: 3  # Set to the number of available nodes to ensure each node has at least one pod
  maxReplicas: 30  # Maximum pods across the cluster
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
