---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-svc
subjects:
- kind: ServiceAccount
  name: docs
  namespace: docs
roleRef:
  kind: ClusterRole
  name: svc-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: docs
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: docs
subjects:
- kind: ServiceAccount
  name: docs
  namespace: docs
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
