name: ollama-version
on:
  repository_dispatch:
    types: [ollama-version]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions:
  id-token: write
  contents: write
jobs:
  ollama-version:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: main

      - name: Setup Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Process fqdn
        run: |
          export DOMAIN_NAME="${{ vars.OLLAMA_FQDN }}"
          envsubst < ollama-certificate/certificate.yaml > ollama-certificate/certificate.processed.yaml
          mv ollama-certificate/certificate.processed.yaml ollama-certificate/certificate.yaml
          envsubst < ollama/HelmRelease.yaml > ollama/HelmRelease.processed.yaml
          mv ollama/HelmRelease.processed.yaml ollama/HelmRelease.yaml

      - name: Commit and Push Changes
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Process Dispatch"
            git push -f origin main:ollama-version
          fi
