name: Sync Branches with Main

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    name: Sync Branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: List all branches
        id: list-branches
        run: |
          git fetch --all
          git branch -r | grep -v '->' | sed 's/origin\///' | grep -v 'main' > branches.txt
          cat branches.txt

      - name: Sync Each Branch
        run: |
          while IFS= read -r branch; do
            echo "Syncing branch $branch"
            git checkout $branch
            git merge --no-edit origin/main
            git push origin $branch
          done < branches.txt

